events {}

http {
    upstream app1_servers {
        least_conn;
        server app1:5000;
        server app1:5000;
        server app1:5000;
    }

    upstream app2_servers {
        server app2:5000;
    }

    server {
        listen 80;
        server_name localhost;

        location /app1/ {
            rewrite ^/app1/(.*) /$1 break;
            proxy_pass http://app1_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /app2/ {
            rewrite ^/app2/(.*) /$1 break;
            proxy_pass http://app2_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            return 200 "Bienvenue sur le reverse proxy Nginx!\n\nApp1 (TODO API): /app1/\nApp2 (service): /app2/\n";
            add_header Content-Type text/plain;
        }
    }
}